server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /backend/ {
        proxy_pass http://backend:8000/;
        proxy_read_timeout 60s;
    }

    # SPA: cualquier ruta no encontrada regresa a index.html (React Router, si lo usas)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
